version: "3"

services:
  flask:
    container_name: "${FLASK}"
    restart: always
    build: ./flask
    volumes:
      - ./flask/logs:/usr/src/flask_app/logs
    expose:
      - "${FLASK_PORT}"
    env_file:
      - ./.env
    command: gunicorn -c ./gunicorn.conf.py "app:create_app('prod')"
    depends_on:
      - redis
      - mysql

  nginx:
    container_name: "${PROXY}"
    restart: always
    build: ./nginx
    volumes:
      - ./nginx/log:/var/log/nginx
    ports:
      - "${PROXY_PORT}:80"
    depends_on:
      - flask

  mysql:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    container_name: "${MYSQL}"
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql

  redis:
    image: redis:4.0.11-alpine
    container_name: "${REDIS}"
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    expose:
      - "${REDIS_PORT}"

