version: "3"

services:
  flask_app:
    container_name: learn_english
    networks:
      - nginx_network
    restart: always
    build: ./
    volumes:
      - ./logs:/usr/src/flask_app/logs
    ports:
      - "16981:8001"
    command: gunicorn -c ./gunicorn.conf.py 'app:create_app()'

networks:
  nginx_network:
    external: true
